### Hacer login 
POST http://localhost:1234/login
Content-Type: application/json

{
  "email": "miguel@gmail.com",
  "password": "admin123"
}

### Registro de un usuario
POST http://localhost:1234/register
Content-Type: application/json

{
  "username": "juanito123",
  "password": "admin123",
  "first_name": "Juan",
  "last_name" : "González",
  "email" : "juanito@gmail.com"
}

### Recuperar todos los sabores
GET http://localhost:1234/api/flavours

### Recuperar un sabor por id
GET http://localhost:1234/api/flavours/2

### Recuperar todos los sabores por una marca
GET http://localhost:1234/api/flavours?brand=serbetli

### Crear un sabor con POST
POST http://localhost:1234/api/flavours
Content-Type: application/json

{
  "name": "Lemmer",
  "description": "Mermelada de limón",
  "brand": "Serbetli",
  "flavour_categories" : [
    {
      "category_name": "Fresco"
    },
    {
      "category_name": "Afrutado"
    }
  ]
}

### Actualizar los datos de un sabor PATCH
PATCH http://localhost:1234/api/flavours/5
Content-Type: application/json

{
  "description": "Sabor tropical muy fresco y afrutado",
  "flavour_categories" : [
    {
      "category_name": "Especiado"
    },
    {
      "category_name": "Afrutado"
    }
  ]
}

### Actualizar los datos de un sabor PUT
PUT http://localhost:1234/api/flavours/5
Content-Type: application/json

{
  "name": "Lemmer",
  "description": "Mermelada de limón y menta",
  "brand": "Serbetli",
  "flavour_categories" : [
    {
      "category_name": "Fresco"
    },
    {
      "category_name": "Afrutado"
    }
  ]
}

### Borrar un sabor
DELETE http://localhost:1234/api/flavours/5

#####################################################################

### Recuperar todas las mezclas
GET http://localhost:1234/api/mixes

### Recuperar una mezcla por id
GET http://localhost:1234/api/mixes/2

### Recuperar todas las mezclas por un sabor concreto
GET http://localhost:1234/api/mixes?flavour=forever

### Recuperar todas las mezclas por un tipo
GET http://localhost:1234/api/mixes?category=afrutado

### Recuperar todas las mezclas por un tipo y un sabor concreto
GET http://localhost:1234/api/mixes?flavour=jungle&category=afrutado

### Crear una mezcla con POST
POST http://localhost:1234/api/mixes
Content-Type: application/json

{
  "name": "Mezcla definitiva",
  "mix_flavours": [
    {
      "flavour_name": "Jungle",
      "percentage": 33
    },
    {
      "flavour_name": "Richman",
      "percentage": 33
    },
    {
      "flavour_name": "Forever",
      "percentage": 34
    }
  ]
}

### Actualizar los datos de una mezcla PATCH
PATCH http://localhost:1234/api/mixes/3
Content-Type: application/json

{
    "mix_flavours": [
    {
      "flavour_name": "Maca Roll",
      "percentage": 70
    },
    {
      "flavour_name": "Forever",
      "percentage": 30
    }
  ]
}

### Actualizar los datos de una mezcla PUT
PUT http://localhost:1234/api/mixes/3
Content-Type: application/json

{
  "name": "Mezcla favorita",
  "username": "migueliyo",
  "mix_flavours": [
    {
      "flavour_name": "Forever",
      "percentage": 33
    },
    {
      "flavour_name": "Richman",
      "percentage": 33
    },
    {
      "flavour_name": "Maca Roll",
      "percentage": 34
    }
  ]
}

### Agregar un like a una mezcla
POST http://localhost:1234/api/mixes/1/like

### Eliminar un like de una mezcla
DELETE http://localhost:1234/api/mixes/1/like

### Borrar una mezcla
DELETE http://localhost:1234/api/mixes/3

#####################################################################

### Recuperar todos los usuarios
GET http://localhost:1234/api/users

### Recuperar un usuario por id
GET http://localhost:1234/api/users/1

### Recuperar un usuario por email
GET http://localhost:1234/api/users?email=miguel@gmail.com

### Recuperar un usuario por username
GET http://localhost:1234/api/users?username=migueliyo

### Crear un usuario con POST
POST http://localhost:1234/api/users
Content-Type: application/json

{
  "username": "juanito123",
  "password": "admin123",
  "first_name": "Juan",
  "last_name" : "González",
  "email" : "juanito@gmail.com"
}

### Actualizar los datos de un usuario PATCH
PATCH http://localhost:1234/api/users/2
Content-Type: application/json

{
  "username": "juanillo456"
}

### Actualizar los datos de un usuario PUT
PUT http://localhost:1234/api/users/2
Content-Type: application/json

{
  "username": "juanito123",
  "password": "admin456",
  "first_name": "Juan",
  "last_name" : "González",
  "email" : "juanito@gmail.com"
}

### Borrar un usuario
DELETE http://localhost:1234/api/users/2

#####################################################################

### Recuperar todas las entradas
GET http://localhost:1234/api/entries

### Recuperar una entrada por id
GET http://localhost:1234/api/entries/2

### Recuperar todas las entradas por un sabor concreto
GET http://localhost:1234/api/entries?category=limpieza

### Crear una entrada con POST
POST http://localhost:1234/api/entries
Content-Type: application/json

{
  "title": "Las mejores marcas de cachimba de 2024",
  "description": "Las mejores marcas de cachimba de 2024",
  "entry_categories": [
    {
      "category_name": "Curiosidad"
    },
    {
      "category_name": "Cachimbas"
    },
    {
      "category_name": "Actualidad"
    }
  ]
}

### Actualizar los datos de una entrada PATCH
PATCH http://localhost:1234/api/entries/3
Content-Type: application/json

{
  "entry_categories": [
    {
      "category_name": "Curiosidad"
    },
    {
      "category_name": "Cachimbas"
    },
    {
      "category_name": "Lo más nuevo"
    }
  ]
}

### Actualizar los datos de una entrada PUT
PUT http://localhost:1234/api/entries/3
Content-Type: application/json

{
  "username": "migueliyo",
  "title": "Las mejores marcas de cachimba de los últimos años",
  "description": "Las mejores marcas de cachimba de 2024",
  "entry_categories": [
    {
      "category_name": "Curiosidad"
    },
    {
      "category_name": "Cachimbas"
    },
    {
      "category_name": "Actualidad"
    }
  ]
}

### Borrar una entrada
DELETE http://localhost:1234/api/entries/3