version: '1.0'
services:
  db:
    image: mysql
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--default-authentication-plugin=caching_sha2_password"]
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes: 
      - ./bbdd.sql:/docker-entrypoint-initdb.d/bbdd.sql
    ports:
      - 33306:3306
    networks:
      - skynet
  adminer:
    image: adminer
    restart: "no"
    ports:
      - 8181:8080
    networks:
      - skynet    
networks:
  skynet: